name: Realtime_minecraft
version: '1.0-SNAPSHOT'
main: always.io.kr.realtime_minecraft.Realtime_minecraft
api-version: '1.21'
authors: [ Sie ]
description: Realtime sync on minecraft server.
commands:
  realtime:
    description: 시간 동기화 플러그인 제어
    usage: /realtime <start|stop|status>